### ISSUE TITLE
Creating function "Polyline from file" not working properly with 1 data column

### ISSUE THREAD

**Issue by kristsaet** [openfedem/fedem-gui#25] opened 2024-09-26 17:19 UTC
As pr. topic. 

If one import a poly-line from file with only 1 data-channel you are not able to really select which of the data columns to use.
Ideally it should just auto-select the only one actually available in the input-file, or at least let you select it manually.

**Comment by kmokstad** [comment] 2024-09-26 19:05
Didn't quite get this one either. A single-column file will not work, of course. As it needs the first column for the X-axis values (always) and then the 2nd column for the Y-axis values. Only if there are more than two columns in the file it makes sense with some user interaction to choose which column/channel (this has to be column 2 or higher, never column 1 which is reserved for the X-axis).

**Comment by kristsaet** [comment] 2024-09-26 19:49
Once again not very precise explanation. But I ment 1 data column in addition to the time column. I.e. 1 time dependent data channel.

**Comment by kristsaet** [comment] 2024-09-26 19:54
Select button is greyed out:
![image](https://github.com/user-attachments/assets/f4a60807-20f6-4e16-a698-08c369159503)

**Comment by kmokstad** [comment] 2024-09-27 05:28
Yes, and in this case the second column in the file is auto-selected as the data channel (Y-axis values when plotting it). Maybe the confusion is the "Not set" label in the Channel field. It would be better perhaps to actually display the label of that column in the file here (if the file contains one which is not required for two-column files). But the function will/should work as it is now also, at least I could not reproduce any error.

**Comment by kristsaet** [comment] 2024-09-27 05:39
At least it is not possible to get a preview of the file, it shows blank time-axis in this case.
![image](https://github.com/user-attachments/assets/3a8d53a2-cd35-42fd-aadd-4a81e1df851d)

**Comment by kmokstad** [comment] 2024-09-27 07:15
This is probably due to the same error that was fixed in openfedem/fedem-foundation#11. But I'll fix the Channel field such that it will show the label of the data column, if present, and close this issue. Please reopen with more details if the problem persists in the new version.

**Closed** 2024-09-27 13:38 UTC
Labels: bug
